# Generated by Django 3.2.8 on 2021-10-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=900)),
                ('devise', models.CharField(choices=[('Eur', 'Eur'), ('Dollar', 'Dollar'), ('Sol', 'Sol')], default='Eur', max_length=20)),
                ('zone', models.CharField(choices=[('abap', 'abap'), ('algol', 'algol'), ('algol_nu', 'algol_nu'), ('arduino', 'arduino'), ('autumn', 'autumn'), ('borland', 'borland'), ('bw', 'bw'), ('colorful', 'colorful'), ('default', 'default'), ('emacs', 'emacs'), ('friendly', 'friendly'), ('fruity', 'fruity'), ('gruvbox-dark', 'gruvbox-dark'), ('gruvbox-light', 'gruvbox-light'), ('igor', 'igor'), ('inkpot', 'inkpot'), ('lovelace', 'lovelace'), ('manni', 'manni'), ('material', 'material'), ('monokai', 'monokai'), ('murphy', 'murphy'), ('native', 'native'), ('paraiso-dark', 'paraiso-dark'), ('paraiso-light', 'paraiso-light'), ('pastie', 'pastie'), ('perldoc', 'perldoc'), ('rainbow_dash', 'rainbow_dash'), ('rrt', 'rrt'), ('sas', 'sas'), ('solarized-dark', 'solarized-dark'), ('solarized-light', 'solarized-light'), ('stata', 'stata'), ('stata-dark', 'stata-dark'), ('stata-light', 'stata-light'), ('tango', 'tango'), ('trac', 'trac'), ('vim', 'vim'), ('vs', 'vs'), ('xcode', 'xcode'), ('zenburn', 'zenburn')], default='0', max_length=100)),
                ('brower', models.CharField(default='0', max_length=100)),
                ('lender', models.CharField(default='0', max_length=100)),
                ('status', models.CharField(choices=[('Closing', 'Closing'), ('Structuring', 'Structuring'), ('Push', 'Push')], default='Waiting', max_length=20)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
