# Generated by Django 3.2.8 on 2021-10-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_title_snippet_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='language',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.AddField(
            model_name='snippet',
            name='brower',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='devise',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='snippet',
            name='lender',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='snippet',
            name='zone',
            field=models.CharField(choices=[('abap', 'abap'), ('algol', 'algol'), ('algol_nu', 'algol_nu'), ('arduino', 'arduino'), ('autumn', 'autumn'), ('borland', 'borland'), ('bw', 'bw'), ('colorful', 'colorful'), ('default', 'default'), ('emacs', 'emacs'), ('friendly', 'friendly'), ('fruity', 'fruity'), ('gruvbox-dark', 'gruvbox-dark'), ('gruvbox-light', 'gruvbox-light'), ('igor', 'igor'), ('inkpot', 'inkpot'), ('lovelace', 'lovelace'), ('manni', 'manni'), ('material', 'material'), ('monokai', 'monokai'), ('murphy', 'murphy'), ('native', 'native'), ('paraiso-dark', 'paraiso-dark'), ('paraiso-light', 'paraiso-light'), ('pastie', 'pastie'), ('perldoc', 'perldoc'), ('rainbow_dash', 'rainbow_dash'), ('rrt', 'rrt'), ('sas', 'sas'), ('solarized-dark', 'solarized-dark'), ('solarized-light', 'solarized-light'), ('stata', 'stata'), ('stata-dark', 'stata-dark'), ('stata-light', 'stata-light'), ('tango', 'tango'), ('trac', 'trac'), ('vim', 'vim'), ('vs', 'vs'), ('xcode', 'xcode'), ('zenburn', 'zenburn')], default='0', max_length=100),
        ),
    ]
