# Generated by Django 3.2.8 on 2021-10-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20211028_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
    ]
