# Generated by Django 3.2.8 on 2021-10-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_alter_snippet_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
