# Generated by Django 3.2.8 on 2021-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_snippet_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='zone',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Asie', 'Asie'), ('Amerique', 'Amerique')], default='0', max_length=100),
        ),
    ]
