# Generated by Django 3.2.8 on 2021-10-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_alter_snippet_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='montant',
            new_name='amountMoney',
        ),
    ]
