# Generated by Django 3.2.8 on 2021-10-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_rename_amount_snippet_montant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='brower',
            new_name='borower',
        ),
    ]
